# If you change this name also do it in ci_metrics.yml
name: end-to-end

on:
  workflow_dispatch: # Activate this workflow manually
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "e2e/**/*.py"
      - ".github/workflows/e2e.yml"

env:
  PYTHON_VERSION: "3.8"
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  HATCH_VERSION: "1.9.3"

jobs:
  run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: "${{ env.PYTHON_VERSION }}"

    - name: Install Hatch
      run: pip install hatch==${{ env.HATCH_VERSION }}

    - name: Run tests
      run: hatch run test:e2e

    - name: Send event to Datadog
      if: failure() && github.event_name == 'schedule'
      uses: masci/datadog@a5d283e78e33a688ed08a96ba64440505e645a8c # v1.7.1
      with:
        api-key: ${{ secrets.CORE_DATADOG_API_KEY }}
        api-url: https://api.datadoghq.eu
        events: |
          - title: "${{ github.workflow }} workflow"
            text: "Job ${{ github.job }} in branch ${{ github.ref_name }}"
            alert_type: "error"
            source_type_name: "Github"
            host: ${{ github.repository_owner }}
            tags:
              - "project:${{ github.repository }}"
              - "job:${{ github.job }}"
              - "run_id:${{ github.run_id }}"
              - "workflow:${{ github.workflow }}"
              - "branch:${{ github.ref_name }}"
              - "url:https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
