name: Check Release Notes

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - labeled
      - unlabeled
    paths-ignore:
      - "**.py"
      - "pyproject.toml"
      - "!.github/**/*.py"

permissions:
  contents: read

jobs:
  reno:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Skip mandatory job
        run: echo "Skipped!"
